### ISSUE TITLE
error when trying to compile esp32 port

### ISSUE THREAD

**Issue by uraich** [lvgl/lv_binding_micropython#189]
When trying to compile the esp32 port of lv_micropython I get this error:
Traceback (most recent call last):
  File "/opt/ucc/micros/esp32/lv_micropython/lib/lv_bindings/gen/gen_mpy.py", line 2665, in <module>
    try_generate_structs_from_first_argument()
  File "/opt/ucc/micros/esp32/lv_micropython/lib/lv_bindings/gen/gen_mpy.py", line 2600, in try_generate_structs_from_first_argument
    try_generate_type(args[0].type)
  File "/opt/ucc/micros/esp32/lv_micropython/lib/lv_bindings/gen/gen_mpy.py", line 2057, in try_generate_type
    try_generate_struct(type, structs[type]) if type in structs else None
  File "/opt/ucc/micros/esp32/lv_micropython/lib/lv_bindings/gen/gen_mpy.py", line 1759, in try_generate_struct
    converted = try_generate_type(decl.type)
  File "/opt/ucc/micros/esp32/lv_micropython/lib/lv_bindings/gen/gen_mpy.py", line 2038, in try_generate_type
    return try_generate_type(type_ast.type)
  File "/opt/ucc/micros/esp32/lv_micropython/lib/lv_bindings/gen/gen_mpy.py", line 2094, in try_generate_type
    if try_generate_struct(type, structs[type]):
  File "/opt/ucc/micros/esp32/lv_micropython/lib/lv_bindings/gen/gen_mpy.py", line 1769, in try_generate_struct
    try_generate_struct(type_name, decl.type.type)
  File "/opt/ucc/micros/esp32/lv_micropython/lib/lv_bindings/gen/gen_mpy.py", line 1750, in try_generate_struct
    return try_generate_type(structs[struct.name])
KeyError: None

**Comment by uraich** [comment]
Hi Amir,
Thanks for your help, I finally made it!
When going to version 4.2 of esp-idf I had different problems: The newest version of esp-idf uses compiler version  esp-2021r1-8.4.0 while version 4.2 requires compiler version esp-2020r3-8.4.0!
Using the newest esp-idf with micropython (without lvgl) I also used the 2021 version of gcc.
I think we should quickly move to the new esp-idf because I might not be the only one who is going to run into these type of problems.
