### ISSUE TITLE
Missing machine.Timer implementation!

### ISSUE THREAD

**Issue by carey-zhou** [lvgl/lv_binding_micropython#356]
build `micropython` successfully
```
export PATH=/path/to/host/bin:$PATH
make -C ports/unix CROSS_COMPILE=arm-none-linux-gnueabihf-
```
Run `fb_test.py` failed
```
 micropython fb_test.py
````

Error output:
```
# micropython fb_test.py
Traceback (most recent call last):
  File "fb_test.py", line 6, in <module>
  File "lv_utils.py", line 45, in <module>
RuntimeError: Missing machine.Timer implementation!
```

**Comment by kdschlosser** [comment]
the unix port only works on unix like OS's that are 100% compatible with the Linux standard. . It doesn't work on OS's like macOS. This is because macOS is not a 100% Linux compatible.
